/**
 * @fileoverview gRPC-Web generated client stub for hello
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: protobuf/hello.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as protobuf_hello_pb from '../protobuf/hello_pb';


export class GreeterClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSayHello = new grpcWeb.MethodDescriptor(
    '/hello.Greeter/SayHello',
    grpcWeb.MethodType.UNARY,
    protobuf_hello_pb.HelloRequest,
    protobuf_hello_pb.HelloReply,
    (request: protobuf_hello_pb.HelloRequest) => {
      return request.serializeBinary();
    },
    protobuf_hello_pb.HelloReply.deserializeBinary
  );

  sayHello(
    request: protobuf_hello_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null): Promise<protobuf_hello_pb.HelloReply>;

  sayHello(
    request: protobuf_hello_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: protobuf_hello_pb.HelloReply) => void): grpcWeb.ClientReadableStream<protobuf_hello_pb.HelloReply>;

  sayHello(
    request: protobuf_hello_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: protobuf_hello_pb.HelloReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/hello.Greeter/SayHello',
        request,
        metadata || {},
        this.methodDescriptorSayHello,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/hello.Greeter/SayHello',
    request,
    metadata || {},
    this.methodDescriptorSayHello);
  }

  methodDescriptorSayHelloServerStream = new grpcWeb.MethodDescriptor(
    '/hello.Greeter/SayHelloServerStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    protobuf_hello_pb.HelloRequest,
    protobuf_hello_pb.HelloReply,
    (request: protobuf_hello_pb.HelloRequest) => {
      return request.serializeBinary();
    },
    protobuf_hello_pb.HelloReply.deserializeBinary
  );

  sayHelloServerStream(
    request: protobuf_hello_pb.HelloRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<protobuf_hello_pb.HelloReply> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/hello.Greeter/SayHelloServerStream',
      request,
      metadata || {},
      this.methodDescriptorSayHelloServerStream);
  }

}

